// Package plugin defines the contract every vendor plugin must satisfy.
// Native Go plugins implement VendorPlugin directly.
// WASM plugins are wrapped by the wasm.Loader which presents the same interface.
package plugin

import "github.com/noctuary-io/noctuary-plugins/schema"

// RuleType describes how a FingerprintRule matches against a log body.
type RuleType string

const (
	// RuleTypeFieldName matches when body contains "key=" — field presence regardless of value.
	RuleTypeFieldName RuleType = "field_name"
	// RuleTypeFieldValue matches when body contains an exact "key=value" token.
	RuleTypeFieldValue RuleType = "field_value"
	// RuleTypePrefix matches when body starts with value.
	RuleTypePrefix RuleType = "prefix"
	// RuleTypeSubstring matches when body contains value anywhere.
	RuleTypeSubstring RuleType = "substring"
	// RuleTypeRegex matches when body matches the compiled regular expression.
	RuleTypeRegex RuleType = "regex"
	// RuleTypeAttributeKey matches when Attributes[value] is non-empty.
	// Use for plugins that receive OTel SDK logs where structured fields
	// arrive in attributes rather than the log body text.
	RuleTypeAttributeKey RuleType = "attribute_key"
	// RuleTypeServiceName matches when ParsedOTelLog.ServiceName equals value (exact match).
	// Use for JVM/agent-instrumented services where the OTel body is just the
	// log message text, with no vendor-identifiable class names or structured fields.
	RuleTypeServiceName RuleType = "service_name"
)

// FingerprintRule is one discriminating feature that identifies a vendor's log output.
// Rules are generated by the LLM bootstrapping loop and reviewed by a human.
// Weight contributes to the vendor confidence score; scores are capped at 1.0.
type FingerprintRule struct {
	Type   RuleType `json:"type"`
	Value  string   `json:"value"`
	Weight float64  `json:"weight"`
}

// VendorPlugin is the interface every vendor plugin must implement.
// The hot path calls only Fingerprints() (for routing) and Match() (for extraction).
// LLMs are not involved at runtime.
type VendorPlugin interface {
	Vendor() string
	Version() string

	// Fingerprints returns lightweight rules used by the router to decide
	// whether to invoke this plugin for a given log line.
	Fingerprints() []FingerprintRule

	// Match attempts to extract a ContextEvent from the log line.
	// Returns (nil, nil) when the line is structurally from this vendor
	// but does not represent a meaningful state change.
	Match(line schema.ParsedOTelLog) (*schema.ContextEvent, error)
}
